import test from "node:test";
import assert from "node:assert";
import dotenv from "dotenv";
import mongoose from "mongoose";
import app from "../src/app.js";
import { User } from "../src/models/user.models.js";

// Load environment variables
dotenv.config();

// Standardize mongoose settings for testing
mongoose.set("strictQuery", true);

test.describe("Project Management API Integration Tests", () => {
    let server;
    let baseUrl;
    let cookies = [];
    let lastUnhashedToken = null;

    // Test credentials
    const testUsername = `testuser_${Date.now()}`;
    const testEmail = `${testUsername}@example.com`;
    const testPassword = "TestPassword123!";
    const newPassword = "NewTestPassword123!";

    // Intercept unhashed tokens generated by user model
    const originalGenerateTemporaryToken = User.prototype.generateTemporaryToken;
    User.prototype.generateTemporaryToken = function() {
        const result = originalGenerateTemporaryToken.apply(this);
        lastUnhashedToken = result.unhashedtoken;
        return result;
    };

    // Helper to send HTTP requests with cookie handling
    async function request(path, options = {}) {
        const url = `${baseUrl}${path}`;
        const headers = options.headers || {};
        
        if (cookies.length > 0) {
            headers["Cookie"] = cookies.join("; ");
        }

        const response = await fetch(url, {
            ...options,
            headers
        });

        // Capture cookies from Set-Cookie headers
        const setCookieHeaders = response.headers.getSetCookie();
        if (setCookieHeaders && setCookieHeaders.length > 0) {
            cookies = setCookieHeaders.map(cookie => cookie.split(";")[0]);
        }

        const text = await response.text();
        let data = null;
        try {
            data = JSON.parse(text);
        } catch (e) {
            data = text;
        }

        return {
            status: response.status,
            data
        };
    }

    test.before(async () => {
        // Connect to Mongo DB
        const mongoUrl = process.env.MONGO_URL;
        if (!mongoUrl) {
            throw new Error("MONGO_URL environment variable is not defined");
        }
        await mongoose.connect(mongoUrl);

        // Clear any leftover test users
        await User.deleteMany({ email: /testuser_.*@example.com/ });

        // Start server on dynamic port
        return new Promise((resolve) => {
            server = app.listen(0, () => {
                const port = server.address().port;
                baseUrl = `http://localhost:${port}`;
                console.log(`Test server running at ${baseUrl}`);
                resolve();
            });
        });
    });

    test.after(async () => {
        // Clean up test user
        await User.deleteMany({ email: testEmail });

        // Close connections
        await mongoose.disconnect();
        if (server) {
            await new Promise((resolve) => server.close(resolve));
        }
    });

    test("1. GET /api/v1/healthcheck -> should return 200 health status", async () => {
        const res = await request("/api/v1/healthcheck");
        assert.strictEqual(res.status, 200);
        assert.strictEqual(res.data.success, true);
        assert.strictEqual(res.data.data.message, "Server is running");
    });

    test("2. POST /api/v1/auth/register -> should register new user and set email verification token", async () => {
        const res = await request("/api/v1/auth/register", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                username: testUsername,
                email: testEmail,
                password: testPassword,
                role: "user"
            })
        });

        assert.strictEqual(res.status, 201, `Failed to register user: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        assert.ok(res.data.data.user);
        assert.strictEqual(res.data.data.user.email, testEmail.toLowerCase());
        assert.ok(lastUnhashedToken, "Email verification token should have been intercepted");
    });

    test("3. GET /api/v1/auth/verify-email/:verificationtoken -> should verify the user email", async () => {
        const tokenToVerify = lastUnhashedToken;
        const res = await request(`/api/v1/auth/verify-email/${tokenToVerify}`);
        
        assert.strictEqual(res.status, 200, `Email verification failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        assert.strictEqual(res.data.data.isEmailVerified, true);

        // Verify state in DB
        const user = await User.findOne({ email: testEmail });
        assert.strictEqual(user.isEmailVerified, true);
        assert.strictEqual(user.emailVerificationToken, undefined);
    });

    test("4. POST /api/v1/auth/login -> should login the verified user and return auth cookies", async () => {
        const res = await request("/api/v1/auth/login", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                email: testEmail,
                password: testPassword
            })
        });

        assert.strictEqual(res.status, 200, `Login failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        assert.ok(res.data.data.user);
        assert.ok(cookies.some(c => c.startsWith("accesstoken=")), "Access token cookie missing");
        assert.ok(cookies.some(c => c.startsWith("refreshtoken=")), "Refresh token cookie missing");
    });

    test("5. POST /api/v1/auth/current-user -> should fetch profile of currently logged-in user", async () => {
        const res = await request("/api/v1/auth/current-user", {
            method: "POST"
        });

        assert.strictEqual(res.status, 200, `Fetch profile failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        assert.strictEqual(res.data.data.email, testEmail.toLowerCase());
    });

    test("6. POST /api/v1/auth/change-password -> should change the current password", async () => {
        const res = await request("/api/v1/auth/change-password", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                oldpassword: testPassword,
                newpassword: newPassword
            })
        });

        assert.strictEqual(res.status, 200, `Change password failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);

        // Verify password correctness in DB
        const user = await User.findOne({ email: testEmail });
        const isNewCorrect = await user.isPasswordCorrect(newPassword);
        assert.strictEqual(isNewCorrect, true);
    });

    test("7. POST /api/v1/auth/forgot-password -> should trigger password reset and send email", async () => {
        lastUnhashedToken = null; // reset token tracker
        const res = await request("/api/v1/auth/forgot-password", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                email: testEmail
            })
        });

        assert.strictEqual(res.status, 200, `Forgot password request failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        assert.ok(lastUnhashedToken, "Reset password token should have been intercepted");
    });

    test("8. POST /api/v1/auth/reset-password/:resettoken -> should reset password using valid token", async () => {
        const tokenToReset = lastUnhashedToken;
        const res = await request(`/api/v1/auth/reset-password/${tokenToReset}`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                newpassword: testPassword
            })
        });

        assert.strictEqual(res.status, 200, `Reset password failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);

        // Verify new password correctness in DB
        const user = await User.findOne({ email: testEmail });
        const isNewCorrect = await user.isPasswordCorrect(testPassword);
        assert.strictEqual(isNewCorrect, true);
    });

    test("9. POST /api/v1/auth/logout -> should clear auth cookies and log user out", async () => {
        const res = await request("/api/v1/auth/logout", {
            method: "POST"
        });

        assert.strictEqual(res.status, 200, `Logout failed: ${JSON.stringify(res.data)}`);
        assert.strictEqual(res.data.success, true);
        
        // Cookies should be cleared, let's verify cookie headers or try a secure request
        const secureRes = await request("/api/v1/auth/current-user", {
            method: "POST"
        });
        assert.strictEqual(secureRes.status, 403, "Should be forbidden after logout");
    });
});
